In [ ]:
import pandas
import re

In [3]:
df = pandas.read_csv(r"C:\Users\Kamal\Downloads\final_translation.csv")

In [4]:
df

,English,Tamil
0,Let's try something.,ஏதாவது முயற்சி செய்யலாம்.
1,I have to go to sleep.,நான் தூங்க செல்ல வேண்டும்.
2,Today is June 18th and it is Muiriel's birthday!,இன்று ஜூன் 18 மற்றும் முரியலின் பிறந்த நாள்!
3,Muiriel is 20 now.,முரியலுக்கு இப்போது 20 வயது.
4,"The password is ""Muiriel"".","கடவுச்சொல் ""முரியல்""."
...,...,...
11099,Don't speak to the driver while he is driving.,வாகனம் ஓட்டும் போது ஓட்டுனரிடம் பேச வேண்டாம்.
11100,The driver was inattentive and could not stop ...,டிரைவர் கவனக்குறைவாக இருந்ததால் சரியான நேரத்தி...
11101,The driver could not distinguish the signal in...,டிரைவரால் மூடுபனியில் சிக்னலை வேறுபடுத்திப் பா...
11102,The driver tipped his cap.,டிரைவர் தொப்பியை சாய்த்தார்.
11103,The driver gestured him out.,ஓட்டுனர் சைகையால் வெளியே காட்டினார்.

In [6]:
# Function to clean text (removes unwanted characters)
def clean_text(text):
    return re.sub(r'[^a-zA-Z0-9\u0B80-\u0BFF\s]', '', text)

# Clean English and Tamil columns
df['English'] = df['English'].apply(clean_text)
df['Tamil'] = df['Tamil'].apply(clean_text)

In [7]:
# Function to check if Tamil text contains English characters
def contains_english(text):
    return bool(re.search(r'[a-zA-Z]', text))

# Filter out rows where Tamil text contains English words
df = df[~df['Tamil'].apply(contains_english)]

In [8]:
df

,English,Tamil
0,Lets try something,ஏதாவது முயற்சி செய்யலாம்
1,I have to go to sleep,நான் தூங்க செல்ல வேண்டும்
2,Today is June 18th and it is Muiriels birthday,இன்று ஜூன் 18 மற்றும் முரியலின் பிறந்த நாள்
3,Muiriel is 20 now,முரியலுக்கு இப்போது 20 வயது
4,The password is Muiriel,கடவுச்சொல் முரியல்
...,...,...
11099,Dont speak to the driver while he is driving,வாகனம் ஓட்டும் போது ஓட்டுனரிடம் பேச வேண்டாம்
11100,The driver was inattentive and could not stop ...,டிரைவர் கவனக்குறைவாக இருந்ததால் சரியான நேரத்தி...
11101,The driver could not distinguish the signal in...,டிரைவரால் மூடுபனியில் சிக்னலை வேறுபடுத்திப் பா...
11102,The driver tipped his cap,டிரைவர் தொப்பியை சாய்த்தார்
11103,The driver gestured him out,ஓட்டுனர் சைகையால் வெளியே காட்டினார்

In [9]:
df.to_csv(r"C:\Users\Kamal\Downloads\final_translation_cleaned.csv", index=False)

In [12]:
df = pandas.read_csv(r"C:\Users\Kamal\Downloads\final_translation_cleaned.csv")

In [13]:
df

,English,Tamil
0,Lets try something,ஏதாவது முயற்சி செய்யலாம்
1,I have to go to sleep,நான் தூங்க செல்ல வேண்டும்
2,Today is June 18th and it is Muiriels birthday,இன்று ஜூன் 18 மற்றும் முரியலின் பிறந்த நாள்
3,Muiriel is 20 now,முரியலுக்கு இப்போது 20 வயது
4,The password is Muiriel,கடவுச்சொல் முரியல்
...,...,...
11071,Dont speak to the driver while he is driving,வாகனம் ஓட்டும் போது ஓட்டுனரிடம் பேச வேண்டாம்
11072,The driver was inattentive and could not stop ...,டிரைவர் கவனக்குறைவாக இருந்ததால் சரியான நேரத்தி...
11073,The driver could not distinguish the signal in...,டிரைவரால் மூடுபனியில் சிக்னலை வேறுபடுத்திப் பா...
11074,The driver tipped his cap,டிரைவர் தொப்பியை சாய்த்தார்
11075,The driver gestured him out,ஓட்டுனர் சைகையால் வெளியே காட்டினார்

In [1]:
from tokenizer import WordLevelTokenizer

In [22]:
# Initialize tokenizers with special tokens
special_tokens = ["<UNK>", "<PAD>", "<SOS>", "<EOS>"]
tamil_tokenizer = WordLevelTokenizer(special_tokens=special_tokens)
english_tokenizer = WordLevelTokenizer(special_tokens=special_tokens)

# Fit tokenizers on the Tamil and English text columns
tamil_tokenizer.fit_on_texts(df['Tamil'])
print("Tamil Vocabulary Size:", len(tamil_tokenizer.word_to_id))

english_tokenizer.fit_on_texts(df['English'])
print("English Vocabulary Size:", len(english_tokenizer.word_to_id))

Tamil Vocabulary Size: 15529
English Vocabulary Size: 8100

In [28]:
tamil_tokenizer.save("tamil_tokenizer.json")
english_tokenizer.save("english_tokenizer.json")

In [7]:
tamil_tokenizer = WordLevelTokenizer.load("tamil_tokenizer.json")
english_tokenizer = WordLevelTokenizer.load("english_tokenizer.json")

In [8]:
english_tokenizer.encode("Hello world")

[1009, 59]

In [5]:
tamil_tokenizer.load("tamil_tokenizer.json")
english_tokenizer.load("english_tokenizer.json")